---
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
- 5.4

env:
  global:
  - PATH=~/bin:~/.composer/vendor/bin:vendor/bin:$PATH
  - TEST_LINT=`true`

matrix:
  fast_finish: true
  include:
  - php: 5.3
    dist: precise
  allow_failures:
    - php: nightly
    - php: 5.3

before_install:
  - echo $PHPUNIT
  - pwd
  - echo $HOME
  - echo $TRAVIS_PHP_VERSION
  - which composer
  - ls /tmp
  - php --ini
  - xdebug=/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
  - if [[ -f $xdebug ]]; then cat $xdebug; cp $xdebug /tmp; phpenv config-rm xdebug.ini; fi
  - xdebug_php=
  - if [[ -f /tmp/xdebug.ini ]]; then xdebug_php='-c /tmp/xdebug.ini'; fi
  - install --directory .travis/bin
  - if [[ -v PHP_CS_FIXER ]]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer; fi
  - if [[ -v PHPUNIT ]]; then wget https://phar.phpunit.de/${PHPUNIT}.phar --output-document=.travis/bin/$PHPUNIT; fi
  - if [[ -v SENSIO_SECURITY ]]; then wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker; fi
  - composer global require --dev friendsofphp/php-cs-fixer:">=1.12" || true
  - composer global require --dev phpstan/phpstan-phpunit || composer global require --dev phpunit/phpunit
  - composer global require --dev sensiolabs/security-checker || composer global require --dev sensiolabs/security-checker:^3.0

install:
  - composer validate
  - composer install --no-scripts --no-progress --no-suggest
  - if [[ -f config/parameters.yml.travis ]]; then cp config/parameters.yml.travis config/parameters.yml; fi
  - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show

before_script:

script:
  - for f in $(find . -path './vendor' -prune -o -path './tests' -prune -o -name \*.php -print) ; do php -l $f ; done # Do this first!
  - if [[ -v TEST_LINT ]]; then for f in $(find ./tests -name \*.php -print); do php -l $f; done; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer --version; fi
  - if [[ -v PHP_CS_FIXER ]]; then php .travis/bin/php-cs-fixer fix --diff --dry-run -vvv --using-cache=no; fi
  - if command -v php-cs-fixer; then php-cs-fixer fix --diff --dry-run -vvv --using-cache=no; fi
  - ls -l --color vendor/friendsofphp/php-cs-fixer/src/Config.php
  - ls -l --color ~/.composer/vendor/friendsofphp/php-cs-fixer/src/Config.php
  # - if command -v phpstan && [[ -f vendor/friendsofphp/php-cs-fixer/src/Config.php ]]; then phpstan analyse -v --level max *.php; fi
  - if command -v phpstan && command -v php-cs-fixer; then phpstan analyse -v --level max *.php; fi
  - if [[ -v PHPUNIT ]]; then php --ini -c /tmp/xdebug.ini; php $xdebug_php .travis/bin/$PHPUNIT; fi
  - php --ini -c /tmp/xdebug.ini
  - php $xdebug_php $(command -v phpunit)
  - phpunit

  - if [[ -v SENSIO_SECURITY ]]; then php .travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock; fi
  - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock ~/.composer/composer.lock
  - security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
    #^ This checks that the application doesn't use dependencies with known security vulnerabilities
  - if [[ -v VENDOR_LINT ]]; then for f in $(find ./vendor -name \*.php); do php -l $f > /dev/null; done; fi
    #^ Should be the last line of install but sometimes long to execute and little can be done for errors found.

after_success:
    - bash <(curl -s https://codecov.io/bash) -s /tmp

# inspirated from:
  # symfony/symfony-demo
  # https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
